### ISSUE TITLE
OffsiteMiddleware is a downloader middleware now

### ISSUE THREAD

**Issue by wRAR** [zytedata/zyte-spider-templates-project#25]
We disable `scrapy.spidermiddlewares.offsite.OffsiteMiddleware` but we should also disable `scrapy.downloadermiddlewares.offsite.OffsiteMiddleware`

**Comment by kmike** [comment]
This is handled by the addon: https://github.com/zytedata/zyte-spider-templates/blob/3f0a47c10de376e68be864e27d38a3520b4eace9/zyte_spider_templates/_addon.py#L147.
